export const CREATE_USER_REQUEST="CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL="CREATE_USER_FAIL";

export const LOGIN_USER_REQUEST="LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL="LOGIN_USER_FAIL";
export const LOGOUT_USER="LOGOUT_USER";

export const PRODUCT_CREATE_REQUEST="PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS="PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL="PRODUCT_CREATE_FAIL";
