export const CREATE_USER_REQUEST="CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL="CREATE_USER_FAIL";

export const LOGIN_USER_REQUEST="LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL="LOGIN_USER_FAIL";
export const LOGOUT_USER="LOGOUT_USER";

export const PRODUCT_CREATE_REQUEST="PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS="PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL="PRODUCT_CREATE_FAIL";

export const LOAD_PRODUCT_REQUEST="LOAD_PRODUCT_REQUEST";
export const LOAD_PRODUCT_SUCCESS="LOAD_PRODUCT_SUCCESS";
export const LOAD_PRODUCT_FAIL="LOAD_PRODUCT_FAIL";

export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_PRODUCT="REMOVE_PRODUCT";
export const INCREACE_QTY="INCREACE_QTY";
export const DECREASE_QTY="DECREASE_QTY"; 
export const CLEAR_CART="CLEAR_CART"; 
